CREATE TABLE tbl_users_registration (
id INT(11) NOT NULL AUTO_INCREMENT,
email_id VARCHAR(100) NULL DEFAULT NULL,
password VARCHAR(72) NULL DEFAULT NULL,
activation_key VARCHAR(100) NULL DEFAULT NULL,
status ENUM(‘Y’,’N’) NULL DEFAULT ‘N’,
PRIMARY KEY (id)
)
COLLATE=’latin1_swedish_ci’
ENGINE=InnoDB
AUTO_INCREMENT=2
